// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for analyzing text content for cognitive biases.
 *
 * The flow takes text as input and uses an LLM to identify potential cognitive biases, outputting
 * an XML-like tagged format indicating the identified biases and their locations within the text.
 *
 * @exports analyzeTextForBias - The main function to trigger the analysis flow.
 * @exports AnalyzeTextForBiasInput - The input type for the analyzeTextForBias function.
 * @exports AnalyzeTextForBiasOutput - The output type for the analyzeTextForBias function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeTextForBiasInputSchema = z.object({
  text: z.string().describe('The text content to analyze for cognitive biases.'),
});
export type AnalyzeTextForBiasInput = z.infer<typeof AnalyzeTextForBiasInputSchema>;

const AnalyzeTextForBiasOutputSchema = z.object({
  analysis: z
    .string()
    .describe(
      'An XML-like tagged output format indicating the identified biases and their locations within the text.'
    ),
});
export type AnalyzeTextForBiasOutput = z.infer<typeof AnalyzeTextForBiasOutputSchema>;

export async function analyzeTextForBias(input: AnalyzeTextForBiasInput): Promise<AnalyzeTextForBiasOutput> {
  return analyzeTextForBiasFlow(input);
}

const analyzeTextForBiasPrompt = ai.definePrompt({
  name: 'analyzeTextForBiasPrompt',
  input: {schema: AnalyzeTextForBiasInputSchema},
  output: {schema: AnalyzeTextForBiasOutputSchema},
  prompt: `You are a cognitive bias detection expert. Analyze the following text content and identify any potential cognitive biases. Output the analysis in an XML-like tagged format, indicating the bias type and its location within the text.\n\nText Content:\n{{{text}}}`,
});

const analyzeTextForBiasFlow = ai.defineFlow(
  {
    name: 'analyzeTextForBiasFlow',
    inputSchema: AnalyzeTextForBiasInputSchema,
    outputSchema: AnalyzeTextForBiasOutputSchema,
  },
  async input => {
    const {output} = await analyzeTextForBiasPrompt(input);
    return output!;
  }
);
